### PR TITLE
Update the runtime

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by hfiguiere** [comment]
freetype finally removed `freetype-config` and package haven't been using pkg-config that has been available for a long time.

**Comment by AsciiWolf** [comment]
Hmm, I wonder what is the issue here. The AppData file was just renamed to metainfo and seems to be correctly installed:
```
 /usr/bin/mkdir -p '/app/share/metainfo'
 /usr/bin/install -c -m 644 manaplus.metainfo.xml '/app/share/metainfo'
```

**Comment by hfiguiere** [comment]
check the `rename-appdata-file` in the manifest. It still use the old name. I wish this was a fatal error.

**Comment by AsciiWolf** [comment]
Oops, thanks! I overlooked this.

**Comment by AsciiWolf** [comment]
Game seems to work fine. :-)

**Pull request merged**
